name: Daily GitHub Issue Digest

on:
  schedule:
    # Run daily at 16:00 UTC (≈ 09:00 PT during Daylight Savings)
    - cron: "0 16 * * *"
  workflow_dispatch: {}

jobs:
  digest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Comma-separated GitHub search queries (each will be queried and results merged)
      # Reference: https://docs.github.com/search-github/searching-on-github/searching-issues-and-pull-requests
      SEARCH_QUERIES: >-
        org:your-org is:issue is:open no:assignee label:"priority: high" -label:"in progress",
        user:your-username is:issue is:open no:assignee label:P0,
        repo:owner/repo is:issue is:open no:assignee label:P1 -label:wip

      # High priority labels (case-insensitive, comma-separated)
      PRIORITY_LABELS: "priority: high,P0,P1,urgent"

      # Labels to exclude (comma-separated)
      EXCLUDE_LABELS: in progress,wip,blocked

      # Usernames to exclude if assigned (comma-separated)
      EXCLUDE_ASSIGNEES: your-username,dependabot

      # Maximum number of issues per run (after merging results)
      MAX_ISSUES: "100"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Generate digest HTML
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SEARCH_QUERIES: ${{ env.SEARCH_QUERIES }}
          PRIORITY_LABELS: ${{ env.PRIORITY_LABELS }}
          EXCLUDE_LABELS: ${{ env.EXCLUDE_LABELS }}
          EXCLUDE_ASSIGNEES: ${{ env.EXCLUDE_ASSIGNEES }}
          MAX_ISSUES: ${{ env.MAX_ISSUES }}
        run: |
          python digest.py --out digest.html

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "[Daily GitHub Issue Digest] $(date -u +"%Y-%m-%d")"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          html_body: file://digest.html
