name: Daily GitHub Issue Digest

on:
  schedule:
    # Run daily at 16:00 UTC (≈ 09:00 PT during Daylight Savings)
    - cron: "0 16 * * *"
  workflow_dispatch: {}

jobs:
  digest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEARCH_QUERIES: ${{ secrets.SEARCH_QUERIES || 'is:issue is:open no:assignee label:"good first issue"' }}
      PRIORITY_LABELS: ${{ secrets.PRIORITY_LABELS || 'priority:p0,priority:p1,enhancement,feature,performance' }}
      EXCLUDE_LABELS: ${{ secrets.EXCLUDE_LABELS || 'low-priority' }}
      PR_QUERIES: ${{ secrets.PR_QUERIES || 'is:pr is:open' }}
      EXCLUDE_ASSIGNEES: ${{ secrets.EXCLUDE_ASSIGNEES || '' }}
      MAX_ISSUES: "10"
      MAX_PRS: "10"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Set date env (UTC)
        run: echo "TODAY=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Generate digest HTML
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SEARCH_QUERIES: ${{ env.SEARCH_QUERIES }}
          PR_QUERIES: ${{ env.PR_QUERIES }}
          PRIORITY_LABELS: ${{ env.PRIORITY_LABELS }}
          EXCLUDE_LABELS: ${{ env.EXCLUDE_LABELS }}
          EXCLUDE_ASSIGNEES: ${{ env.EXCLUDE_ASSIGNEES }}
          MAX_ISSUES: ${{ env.MAX_ISSUES }}
          MAX_PRS: ${{ env.MAX_PRS }}
        run: |
          python digest.py --out digest.html

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "[Daily GitHub Issue Digest] ${{ env.TODAY }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          html_body: file://digest.html
